export const typeClasses: Record<string, { border: string; bg: string }> = {
    grass: { border: 'border-green-300', bg: 'bg-green-300' },
    fire: { border: 'border-red-300', bg: 'bg-red-300' },
    water: { border: 'border-blue-300', bg: 'bg-blue-300' },
    electric: { border: 'border-yellow-300', bg: 'bg-yellow-300' },
    bug: { border: 'border-lime-300', bg: 'bg-lime-300' },
    poison: { border: 'border-purple-300', bg: 'bg-purple-300' },
    ground: { border: 'border-amber-300', bg: 'bg-amber-300' },
    fairy: { border: 'border-pink-300', bg: 'bg-pink-300' },
    normal: { border: 'border-gray-300', bg: 'bg-gray-300' },
    fighting: { border: 'border-orange-300', bg: 'bg-orange-300' },
    psychic: { border: 'border-fuchsia-300', bg: 'bg-fuchsia-300' },
    rock: { border: 'border-stone-300', bg: 'bg-stone-300' },
    ghost: { border: 'border-indigo-300', bg: 'bg-indigo-300' },
    ice: { border: 'border-cyan-300', bg: 'bg-cyan-300' },
    dragon: { border: 'border-violet-300', bg: 'bg-violet-300' },
    dark: { border: 'border-slate-300', bg: 'bg-slate-300' },
    steel: { border: 'border-zinc-300', bg: 'bg-zinc-300' },
}